FROM node:14.9-buster-slim
MAINTAINER "Mahesh" "mahesh@ilimi.in"
RUN sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list \
    && sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list \
    && sed -i '/buster-updates/d' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install zip -y
RUN mkdir -p /opt/telemetry
ADD src /opt/telemetry/
WORKDIR /opt/telemetry/
RUN npm install
WORKDIR /opt
CMD ["zip", "-r", "telemetry-service.zip", "telemetry"]
